{% set name = "trogon" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trogon-{{ version }}.tar.gz
  sha256: fd1abfeb7b15d79d6e6cfc9e724aad2a2728812e4713a744d975f133e7ec73a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - textual >=0.26.0
    - click >=8.0.0

test:
  imports:
    - trogon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Textualize/trogon
  summary: Automatically generate a Textual TUI for your Click CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
